### ISSUE TITLE
Running error:No such file or directory: 'cards.json'

### ISSUE THREAD

**Issue by Lawliar** [rmnvncnt/pystone#1]
First run this program,and this error just popped out.
<pre>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/usr/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 153, in crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 38, in from_settings
    mw = mwcls()
  File "/home/lcm/Desktop/data/pystone/pystone/pipelines.py", line 17, in __init__
    self.card_list = self.loadcards()
  File "/home/lcm/Desktop/data/pystone/pystone/pipelines.py", line 21, in loadcards
    with open('cards.json') as f:
exceptions.IOError: [Errno 2] No such file or directory: 'cards.json'
2017-06-27 20:10:11 [twisted] CRITICAL: 
</pre>

and stopped running. Does anyone have any idea?

**Comment by rmnvncnt** [comment]
Try to rename refs.json as cards.json. I can't fix this right now, but I'll
do it in a few days !

Le mer. 28 juin 2017 12:12, Liu changming <notifications@github.com> a
écrit :

**Comment by rmnvncnt** [comment]
Actually, you may not have run the command from the directory containing `spiders.py`. I should work now!
